# Generated by Django 6.0.5 on 2026-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Admin", "admin"), ("Staff", "staff")],
                default="admin",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
