# Generated by Django 6.0.5 on 2026-05-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_category_alter_user_role_hscode"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hscode",
            name="hscode_hs_code_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="hscode",
            name="hscode_description_trgm_idx",
        ),
    ]
