# Generated by Django 6.0.5 on 2026-05-31 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_hscode_hscode_hs_code_trgm_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HsCodeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hs_code_file", models.FileField(upload_to="hs_code")),
            ],
        ),
        migrations.AddField(
            model_name="hscode",
            name="hs_code_file",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.hscodefile",
            ),
            preserve_default=False,
        ),
    ]
