# Generated by Django 6.0.5 on 2026-06-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hscodefile_hscode_hs_code_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hscode',
            constraint=models.UniqueConstraint(fields=('hs_code',), name='unique_hs_code'),
        ),
    ]
